### ISSUE TITLE
(Bitdefender) Antivirus Issue, can barely download it let alone install & mod it to SPORE without a .dll issue.

### ISSUE THREAD

**Issue by maxprogramm3r** [Rosalie241/SporeAutoSave#3]
Title explains all. For me personally installing the mod was difficult to even exclude it, when finally downloaded and constantly excluded and even with antivirus turned off, the file's .dll file wont even install because of pathing. Absolutely uninstallable.
![Screenshot 2024-07-09 103246](https://github.com/Rosalie241/SporeAutoSave/assets/175138542/bae16646-8ec4-4487-97ad-770a324621bd)

**Comment by Rosalie241** [comment]
SporeAutoSave is opensource, you can view the code and build it yourself if you want to, anti-virus usually gives false positives so there's nothing I can do.

**Comment by maxprogramm3r** [comment]
Am I able to just package the open-source code as perhaps a zip and then to a .sporemod? I don't have any previous knowledge on the subject besides .jar files.
________________________________

**Comment by Rosalie241** [comment]
No, you'll have to build it with visual studio but you'll have to figure that out on your own.

Just whitelist the mod in your anti-virus and it'll work fine.
